# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: Kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: image-backend
  name: image-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: image-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: Kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (HEAD)
        instrumentation.opentelemetry.io/inject-python: "true"
      creationTimestamp: null
      labels:
        io.kompose.network/imageserviceapp-default: "true"
        io.kompose.service: image-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - python3 manage.py runserver 0.0.0.0:8000 --noreload
          image: ${REPOSITORY_PREFIX}/pythonsampleapp/image-service:latest
          name: image-service-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
          env:
            - name: S3_BUCKET
              value: ${S3_BUCKET}
            - name: POSTGRES_DATABASE
              value: vehicle_inventory
            - name: POSTGRES_PASSWORD
              value: ${POSTGRES_PASSWORD}
            - name: POSTGRES_USER
              value: djangouser
#             Setting PYTHONPATH is currently required due to the issue in OTel: open-telemetry/opentelemetry-operator#2302
            - name: PYTHONPATH
              value: "/image-service-app"
            - name: DJANGO_SETTINGS_MODULE
              value: "ImageServiceApp.settings"
            - name: OTEL_TRACES_SAMPLER
              value: "xray"
      restartPolicy: Always
status: {}
