# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: Kompose convert -f docker-compose.yaml
    kompose.version: 1.31.2 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: image-backend
  name: image-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: image-backend
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: Kompose convert -f docker-compose.yaml
        kompose.version: 1.31.2 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/imageserviceapp-default: "true"
        io.kompose.service: image-backend
    spec:
      containers:
        - args:
            - sh
            - -c
            - python3 manage.py migrate --noinput; python3 manage.py collectstatic --noinput; python3 manage.py runserver 0.0.0.0:8000
          image: ${REPOSITORY_PREFIX}/pythonsampleapp/image-service:latest
          name: image-service-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
